apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-service
  namespace: refundai   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-service
  template:
    metadata:
      labels:
        app: dashboard-service
    spec:
      containers:
        - name: dashboard-service
          image: ghcr.io/arshadm25/dashboard:v1
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: dashboard-service-env
      imagePullSecrets:
        - name: ghcr-secret