apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: refundai
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiYXJzaGFkbTI1IiwicGFzc3dvcmQiOiJnaHBfeUtBWjlHMmhvclg4NjZCdU95UjhRSzNIbHd1SjZHNFFjbzNCIiwiZW1haWwiOiJ5b3VyQGVtYWlsLmNvbSIsImF1dGgiOiJZWEp6YUdGa2JUSTFPbWRvY0Y5NVMwRmFPVWN5YUc5eVdEZzJOa0oxVDNsU09GRkxNMGhzZDNWS05rYzBVV052TTBJPSJ9fX0=

